config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"
  root "static_pages#index"

  resources :documents

  resources :users, only: [:create]

  devise_scope :user do
    get "login", to: "users/sessions#new"
    get "logout", to: "users/sessions#destroy"
    get "signup", to: "users/registrations#new"
  end

  get "users/login", redirect_to: "/login"

  devise_for :users, controllers: {
                       sessions: "users/sessions",
                       registrations: "users/registrations",
                     }

  get "/about" => "static_pages#about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # create user session
  # helper_method :current_user
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    if user_signed_in?
      @documents = Document.all.where(user_id: current_user.id)
    else
      @documents = []
    end
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: "Document was successfully created." }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: "Document was successfully updated." }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: "Document was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def user
    current_user
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_document
    @document = Document.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def document_params
    params.require(:document).permit(:title, :body, :private, :user_id)
  end
end

app/controllers/graphql_controller.rb
class GraphqlController < ApplicationController
  skip_before_action :verify_authenticity_token

  def execute
    variables = ensure_hash(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      current_user: current_user,
    }
    result = DocifySchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  rescue => e
    raise e unless Rails.env.development?
    handle_error_in_development e
  end

  private

  # Handle form data, JSON body, or a blank value
  def ensure_hash(ambiguous_param)
    case ambiguous_param
    when String
      if ambiguous_param.present?
        ensure_hash(JSON.parse(ambiguous_param))
      else
        {}
      end
    when Hash, ActionController::Parameters
      ambiguous_param
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{ambiguous_param}"
    end
  end

  def handle_error_in_development(e)
    logger.error e.message
    logger.error e.backtrace.join("\n")

    render json: {error: {message: e.message, backtrace: e.backtrace}, data: {}}, status: 500
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to "/documents", notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { redirect_to "/signup" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/documents/_form.html.erb
<%= form_with(model: document, local: true, user_path: :user_path) do |form| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= form.label :title %>
    <%= form.text_field :title, id: :document_title %>

    <%= form.label :body %>
    <%= form.text_field :body, id: :document_body %>

    <%= form.label :private %>
    <%= form.check_box :private, id: :document_private %>

    <%= form.hidden_field :user_id, :value => current_user.id %>
    <%= form.submit %>
<% end %>

app/views/documents/edit.html.erb
<%# <%= render 'form', document: @document %>
<main id="root"></main>

<%= link_to 'Show', @document %>
<%= link_to 'Back', documents_path %>

<%= javascript_include_tag 'editor' %>

app/views/documents/index.html.erb
<main class="documents">
  <%# <% if can? :read, @documents %>

  <% if @documents.length > 0  %>
    <% @documents.each do |document| %>

      <%= link_to document do %>
        <div class="document">
          <h2 class="document-title"><%= document.title %></h2>
          <p class="document-body"><%= truncate(document.body, :length => 100, :separator => ' ', :omission => '...') %></p>
        </div>
      <% end %>

    <% end %>
  <% end %>
  <%# <% end %> 

  <%# <% if can? :create, @document %> 
    <button class="create-document"><%= link_to '+', new_document_path %></button>
  <%# <% end %> 
</main>

app/views/documents/new.html.erb
<main id  ="document">
  <%= render 'form', document: @document %>
</main>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<main id="document">
  <div class="document-body">
    <h1><%= @document.title %></h1>

    <p><%= @document.body %></p>

  </div>
</main>
  <div class="navigation-links">
    <%= link_to 'Back', documents_path %>
    <%= link_to 'Edit', edit_document_path(@document) %> 
  </div>

<script src="../../assets/javascripts/editor">

app/views/layouts/_header.html.erb
<% if current_user %>

  <nav class="logged-in">
    <li><a class="logo" href="/" title="Home">Docify</a></li>
    <li><a href="/about" title="About">About</a></li>
    <li><a href="/documents" title="Documents">Documents</a></li>
    <li><a href="/logout">Logout</a></li>
  </nav>

  <% else %>

    <nav>
      <li><a class="logo" href="/" title="Home">Docify</a></li>
      <li><a href="/about" title="About">About</a></li>
      <li><a href="/signup" title="Signup">Signup</a></li>
      <li><a href="/login" title="Login">Login</a></li>
    </nav>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Docify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/about.html.erb
<main id="about">
  <div class="about-text">
    <h1>About</h1>
    <p>
      Lorem ipsum dolor amet hell of glossier heirloom, tote bag coloring book migas authentic fingerstache intelligentsia selvage irony woke kogi. 
      Readymade four loko prism lumbersexual tumblr distillery. Readymade trust fund bushwick echo park twee wolf aesthetic vice swag iPhone pickled. 
      Bespoke kitsch DIY asymmetrical affogato cardigan vape sartorial aesthetic direct trade sustainable scenester 90's cold-pressed lyft.
    </p>
  </div>
</main>

app/views/static_pages/index.html.erb
<main id="root"></main>

<%= javascript_include_tag 'editor' %>